enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

#  │ Revanced Extenends here │       RVX
[YouTube]
app-name = "Yomaru"
rv-brand = "Revanced"
version = "auto"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = ""
included-patches = ""

#  │ Revanced Extenends here │       RVX
[RvX] #
app-name = "Yomaru"
rv-brand = "Ext-rvx"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"                                                # apk = "apk" or magisk zip = "module"
apkmirror-arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = ""
included-patches = ""
# included-patches = "'Remove player controls background' 'Custom branding' 'Enable slide to seek'"
# excluded-patches = "'Disable auto captions' 'Hide captions button' 'Disable rolling number animations' 'Hide album cards' 'Hide filter bar' 'Enable debugging'"

# you can use rvmm-config-gen to generate a config
